pipelines:
  default:
    - step:
        name: Build Engine (Windows)
        runs-on:
          - self.hosted
          - windows

        script:
        - mkdir .\kOS\build
        - cd .\kOS\build
        - cmake -S ..\ -B .
        - cmake --build . --config Release -- /m


        - cd ../bin
        - mkdir -p ..\test-results
        - .\Release\Kos_test.exe --gtest_output=xml:..\test-results\report.xml

  pull-requests:
    "**":
      - step:
          name: Build Engine (PR Check)
          runs-on:
            - self.hosted
            - windows
          script:
          - mkdir .\kOS\build
          - cd .\kOS\build
          - cmake -S ..\ -B .
          - cmake --build . --config Release -- /m


          - cd ../bin
          - mkdir -p ..\test-results
          - .\Release\Kos_test.exe --gtest_output=xml:..\test-results\report.xml
